CLASS zdelete_data DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zdelete_data IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    DELETE FROM ZSHOP_AS_H54.
    DELETE FROM ZONLINESHOP_H54.
    COMMIT WORK.
  ENDMETHOD.
ENDCLASS.
